controller_list:
  - name: r2_legs_controller
    joints:
      - /r2/left_leg/joint0
      - /r2/left_leg/joint1
      - /r2/left_leg/joint2
      - /r2/left_leg/joint3
      - /r2/left_leg/joint4
      - /r2/left_leg/joint5
      - /r2/left_leg/joint6
      - /r2/right_leg/joint0
      - /r2/right_leg/joint1
      - /r2/right_leg/joint2
      - /r2/right_leg/joint3
      - /r2/right_leg/joint4
      - /r2/right_leg/joint5
      - /r2/right_leg/joint6
    default: true

    all_joints:
      - /r2/left_leg/joint0
      - /r2/left_leg/joint1
      - /r2/left_leg/joint2
      - /r2/left_leg/joint3
      - /r2/left_leg/joint4
      - /r2/left_leg/joint5
      - /r2/left_leg/joint6
      - /r2/right_leg/joint0
      - /r2/right_leg/joint1
      - /r2/right_leg/joint2
      - /r2/right_leg/joint3
      - /r2/right_leg/joint4
      - /r2/right_leg/joint5
      - /r2/right_leg/joint6

    pose_settings:
      radians: false
      max_linear_velocity: 0.04
      max_linear_acceleration: 0.02
      max_rotational_velocity: 3.0
      max_rotational_acceleration: 0.5

    joint_stiffness:
      default:
        radians: false
        natural_frequency: 10.0
        damping_ratio: 1.0
        windup_limit: 5.0
      joints:
        - name: /r2/left_leg/joint4
          radians: false
          natural_frequency: 10.0
          damping_ratio: 2.0
          windup_limit: 5.0
        - name: /r2/right_leg/joint4
          radians: false
          natural_frequency: 10.0
          damping_ratio: 2.0
          windup_limit: 5.0
        - name: /r2/left_leg/joint6
          radians: false
          natural_frequency: 30.0
          damping_ratio: 5.0
          windup_limit: 5.0
        - name: /r2/right_leg/joint6
          radians: false
          natural_frequency: 30.0
          damping_ratio: 5.0
          windup_limit: 5.0

    joint_torque:
      default:
        max_torque: 30.0

    joint_speed:
      default:
        radians: true
        velocity_limit: 1.0
        acceleration_limit: 0.5
