controller_list:
  - name: r2_legs_controller
    joints:
      - virtual_world
      - /r2/left_leg/joint0
      - /r2/left_leg/joint1
      - /r2/left_leg/joint2
      - /r2/left_leg/joint3
      - /r2/left_leg/joint4
      - /r2/left_leg/joint5
      - /r2/left_leg/joint6
      - /r2/right_leg/joint0
      - /r2/right_leg/joint1
      - /r2/right_leg/joint2
      - /r2/right_leg/joint3
      - /r2/right_leg/joint4
      - /r2/right_leg/joint5
      - /r2/right_leg/joint6
      - /r2/waist/joint0
      - /r2/left_leg/gripper/joint0
      - /r2/left_leg/gripper/joint1
      - /r2/left_leg/gripper/joint2
      - /r2/right_leg/gripper/joint0
      - /r2/right_leg/gripper/joint1
      - /r2/right_leg/gripper/joint2
    default: true

    all_joints:
      - /r2/waist/joint0
      - /r2/left_arm/joint0
      - /r2/left_arm/joint1
      - /r2/left_arm/joint2
      - /r2/left_arm/joint3
      - /r2/left_arm/joint4
      - /r2/left_arm/wrist/pitch
      - /r2/left_arm/wrist/yaw
      - /r2/right_arm/joint0
      - /r2/right_arm/joint1
      - /r2/right_arm/joint2
      - /r2/right_arm/joint3
      - /r2/right_arm/joint4
      - /r2/right_arm/wrist/pitch
      - /r2/right_arm/wrist/yaw
      - /r2/neck/joint2
      - /r2/neck/joint1
      - /r2/neck/joint0
      - /r2/left_arm/hand/ringlittle/little
      - /r2/left_arm/hand/ringlittle/ring
      - /r2/left_arm/hand/middle/medial
      - /r2/left_arm/hand/middle/proximal
      - /r2/left_arm/hand/middle/yaw
      - /r2/left_arm/hand/index/medial
      - /r2/left_arm/hand/index/proximal
      - /r2/left_arm/hand/index/yaw
      - /r2/left_arm/hand/thumb/distal
      - /r2/left_arm/hand/thumb/medial
      - /r2/left_arm/hand/thumb/proximal
      - /r2/left_arm/hand/thumb/roll
      - /r2/right_arm/hand/ringlittle/little
      - /r2/right_arm/hand/ringlittle/ring
      - /r2/right_arm/hand/middle/medial
      - /r2/right_arm/hand/middle/proximal
      - /r2/right_arm/hand/middle/yaw
      - /r2/right_arm/hand/index/medial
      - /r2/right_arm/hand/index/proximal
      - /r2/right_arm/hand/index/yaw
      - /r2/right_arm/hand/thumb/distal
      - /r2/right_arm/hand/thumb/medial
      - /r2/right_arm/hand/thumb/proximal
      - /r2/right_arm/hand/thumb/roll
      - /r2/left_leg/joint0
      - /r2/left_leg/joint1
      - /r2/left_leg/joint2
      - /r2/left_leg/joint3
      - /r2/left_leg/joint4
      - /r2/left_leg/joint5
      - /r2/left_leg/joint6
      - /r2/right_leg/joint0
      - /r2/right_leg/joint1
      - /r2/right_leg/joint2
      - /r2/right_leg/joint3
      - /r2/right_leg/joint4
      - /r2/right_leg/joint5
      - /r2/right_leg/joint6

    pose_settings:
      radians: false
      max_linear_velocity: 0.04
      max_linear_acceleration: 0.02
      max_rotational_velocity: 3.0
      max_rotational_acceleration: 0.5

    joint_stiffness:
      default:
        radians: false
        natural_frequency: 10.0
        damping_ratio: 1.0
        windup_limit: 5.0
      joints:
        - name: /r2/left_leg/joint4
          radians: false
          natural_frequency: 10.0
          damping_ratio: 2.0
          windup_limit: 5.0
        - name: /r2/right_leg/joint4
          radians: false
          natural_frequency: 10.0
          damping_ratio: 2.0
          windup_limit: 5.0
        - name: /r2/left_leg/joint6
          radians: false
          natural_frequency: 30.0
          damping_ratio: 5.0
          windup_limit: 5.0
        - name: /r2/right_leg/joint6
          radians: false
          natural_frequency: 30.0
          damping_ratio: 5.0
          windup_limit: 5.0

    joint_torque:
      default:
        max_torque: 30.0

    joint_speed:
      default:
        radians: true
        velocity_limit: 1.0
        acceleration_limit: 0.5