left_leg:
  kinematics_solver: moveit_r2_kinematics/MoveItR2ChainKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
right_leg:
  kinematics_solver: moveit_r2_kinematics/MoveItR2ChainKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
legs:
  kinematics_solver: moveit_r2_kinematics/MoveItR2TreeKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3